#ifndef NETSNMPMANAGER_GLOBAL_H
#define NETSNMPMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETSNMPMANAGER_LIBRARY)
#  define NETSNMPMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETSNMPMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETSNMPMANAGER_GLOBAL_H
