get_filename_component(cpdlc_CURRENTDIR ${CMAKE_CURRENT_LIST_FILE} PATH)

include_directories("${cpdlc_CURRENTDIR}")
include_directories("${cpdlc_CURRENTDIR}/src")

if(NOT COMMAND export_group)
    file(GLOB HEADERS "${cpdlc_CURRENTDIR}/src/*.h")
    file(GLOB SOURCES "${cpdlc_CURRENTDIR}/src/*.c")

    list(APPEND HEADERS
        "${cmdline_CURRENTDIR}/CpdlcHelper.h"
        )
    list(APPEND SOURCES
        "${cmdline_CURRENTDIR}/CpdlcHelper.cpp"
        )
else()
    export_group("cpdlc" "cpdlc"
        CpdlcHelper.h
        CpdlcHelper.cpp
        src/ATCdownlinkmessage.h
        src/ATCdownlinkmsgelementid.h
        src/ATCmessageheader.h
        src/ATCuplinkmessage.h
        src/ATCuplinkmsgelementid-seqOf.h
        src/ATCuplinkmsgelementid.h
        src/ATWDistancetolerance.h
        src/ATWalongtrackwaypoint.h
        src/ATWalongtrackwaypointsequence.h
        src/ATWaltitude.h
        src/ATWaltitudesequence.h
        src/ATWaltitudetolerance.h
        src/ATWdistance.h
        src/Aircraftequipmentcode.h
        src/Aircraftflightidentification.h
        src/Aircrafttype.h
        src/Airport.h
        src/Airportdeparture.h
        src/Airportdestination.h
        src/Airwayidentifier.h
        src/Airwayintercept.h
        src/Altimeter.h
        src/Altimeterenglish.h
        src/Altimetermetric.h
        src/Altitude.h
        src/AltitudePosition.h
        src/AltitudeSpeed.h
        src/AltitudeSpeedSpeed.h
        src/AltitudeTime.h
        src/Altitudeflightlevel.h
        src/Altitudeflightlevelmetric.h
        src/Altitudegnssfeet.h
        src/Altitudegnssmeters.h
        src/Altitudeqfe.h
        src/Altitudeqfemeters.h
        src/Altitudeqnh.h
        src/Altitudeqnhmeters.h
        src/Altituderestriction.h
        src/Atiscode.h
        src/BIT_STRING.h
        src/BOOLEAN.h
        src/Beaconcode.h
        src/Beaconcodeoctaldigit.h
        src/COMNAVapproachequipmentavailable.h
        src/COMNAVequipmentstatus.h
        src/DM0NULL.h
        src/DM100NULL.h
        src/DM101NULL.h
        src/DM102NULL.h
        src/DM103NULL.h
        src/DM104NULL.h
        src/DM105NULL.h
        src/DM106NULL.h
        src/DM107NULL.h
        src/DM108NULL.h
        src/DM109NULL.h
        src/DM10Altitude.h
        src/DM110NULL.h
        src/DM111NULL.h
        src/DM112NULL.h
        src/DM113NULL.h
        src/DM114NULL.h
        src/DM115NULL.h
        src/DM116NULL.h
        src/DM117NULL.h
        src/DM118NULL.h
        src/DM119NULL.h
        src/DM11PositionAltitude.h
        src/DM120NULL.h
        src/DM121NULL.h
        src/DM122NULL.h
        src/DM123NULL.h
        src/DM124NULL.h
        src/DM125NULL.h
        src/DM126NULL.h
        src/DM127NULL.h
        src/DM128NULL.h
        src/DM12PositionAltitude.h
        src/DM13TimeAltitude.h
        src/DM14TimeAltitude.h
        src/DM15DistanceoffsetDirection.h
        src/DM16PositionDistanceoffsetDirection.h
        src/DM17TimeDistanceoffsetDirection.h
        src/DM18Speed.h
        src/DM19SpeedSpeed.h
        src/DM1NULL.h
        src/DM20NULL.h
        src/DM21Frequency.h
        src/DM22Position.h
        src/DM23Procedurename.h
        src/DM24Routeclearance.h
        src/DM25NULL.h
        src/DM26PositionRouteclearance.h
        src/DM27DistanceoffsetDirection.h
        src/DM28Altitude.h
        src/DM29Altitude.h
        src/DM2NULL.h
        src/DM30Altitude.h
        src/DM31Position.h
        src/DM32Altitude.h
        src/DM33Position.h
        src/DM34Speed.h
        src/DM35Degrees.h
        src/DM36Degrees.h
        src/DM37Altitude.h
        src/DM38Altitude.h
        src/DM39Speed.h
        src/DM3NULL.h
        src/DM40Routeclearance.h
        src/DM41NULL.h
        src/DM42Position.h
        src/DM43Time.h
        src/DM44Position.h
        src/DM45Position.h
        src/DM46Time.h
        src/DM47Beaconcode.h
        src/DM48Positionreport.h
        src/DM49Speed.h
        src/DM4NULL.h
        src/DM50SpeedSpeed.h
        src/DM51NULL.h
        src/DM52NULL.h
        src/DM53NULL.h
        src/DM54Altitude.h
        src/DM55NULL.h
        src/DM56NULL.h
        src/DM57RemainingfuelRemainingsouls.h
        src/DM58NULL.h
        src/DM59PositionRouteclearance.h
        src/DM5NULL.h
        src/DM60DistanceoffsetDirection.h
        src/DM61Altitude.h
        src/DM62Errorinformation.h
        src/DM63NULL.h
        src/DM64ICAOfacilitydesignation.h
        src/DM65NULL.h
        src/DM66NULL.h
        src/DM67Freetext.h
        src/DM68Freetext.h
        src/DM69NULL.h
        src/DM6Altitude.h
        src/DM70Degrees.h
        src/DM71Degrees.h
        src/DM72Altitude.h
        src/DM73Versionnumber.h
        src/DM74NULL.h
        src/DM75NULL.h
        src/DM76AltitudeAltitude.h
        src/DM77AltitudeAltitude.h
        src/DM78TimeDistanceTofromPosition.h
        src/DM79Atiscode.h
        src/DM7AltitudeAltitude.h
        src/DM80DistanceoffsetDirection.h
        src/DM81NULL.h
        src/DM82NULL.h
        src/DM83NULL.h
        src/DM84NULL.h
        src/DM85NULL.h
        src/DM86NULL.h
        src/DM87NULL.h
        src/DM88NULL.h
        src/DM89NULL.h
        src/DM8Altitude.h
        src/DM90NULL.h
        src/DM91NULL.h
        src/DM92NULL.h
        src/DM93NULL.h
        src/DM94NULL.h
        src/DM95NULL.h
        src/DM96NULL.h
        src/DM97NULL.h
        src/DM98NULL.h
        src/DM99NULL.h
        src/DM9Altitude.h
        src/Degreeincrement.h
        src/Degrees.h
        src/Degreesmagnetic.h
        src/Degreestrue.h
        src/Direction.h
        src/DirectionDegrees.h
        src/Distance.h
        src/Distancekm.h
        src/Distancenm.h
        src/Distanceoffset.h
        src/DistanceoffsetDirection.h
        src/Distanceoffsetkm.h
        src/Distanceoffsetnm.h
        src/EFCtime.h
        src/Errorinformation.h
        src/Fixname.h
        src/Fixnext.h
        src/Fixnextplusone.h
        src/Freetext.h
        src/Frequency.h
        src/Frequencydeparture.h
        src/Frequencyhf.h
        src/Frequencysatchannel.h
        src/Frequencyuhf.h
        src/Frequencyvhf.h
        src/Holdatwaypoint.h
        src/Holdatwaypointsequence.h
        src/Holdatwaypointspeedhigh.h
        src/Holdatwaypointspeedlow.h
        src/Holdclearance.h
        src/IA5String.h
        src/ICAOfacilitydesignation.h
        src/ICAOfacilitydesignationTp4table.h
        src/ICAOfacilityfunction.h
        src/ICAOfacilityidentification.h
        src/ICAOfacilityname.h
        src/ICAOunitname.h
        src/ICAOunitnameFrequency.h
        src/INTEGER.h
        src/Icing.h
        src/Interceptcoursefrom.h
        src/Interceptcoursefromselection.h
        src/Interceptcoursefromsequence.h
        src/Latitude.h
        src/LatitudeLongitude.h
        src/Latitudedegrees.h
        src/Latitudedirection.h
        src/Latitudereportingpoints.h
        src/Latlonreportingpoints.h
        src/Legdistance.h
        src/Legdistanceenglish.h
        src/Legdistancemetric.h
        src/Legtime.h
        src/Legtype.h
        src/Longitude.h
        src/Longitudedegrees.h
        src/Longitudedirection.h
        src/Longitudereportingpoints.h
        src/Minuteslatlon.h
        src/Msgidentificationnumber.h
        src/Msgreferencenumber.h
        src/NULL.h
        src/NativeEnumerated.h
        src/NativeInteger.h
        src/Navaid.h
        src/NumericString.h
        src/OCTET_STRING.h
        src/PDCrevision.h
        src/Placebearing.h
        src/Placebearingdistance.h
        src/Placebearingplacebearing.h
        src/Position.h
        src/PositionAltitude.h
        src/PositionAltitudeAltitude.h
        src/PositionAltitudeSpeed.h
        src/PositionDegrees.h
        src/PositionDistanceoffsetDirection.h
        src/PositionICAOunitnameFrequency.h
        src/PositionProcedurename.h
        src/PositionRouteclearance.h
        src/PositionSpeed.h
        src/PositionSpeedSpeed.h
        src/PositionTime.h
        src/PositionTimeAltitude.h
        src/PositionTimeTime.h
        src/Positioncurrent.h
        src/Positionreport.h
        src/Predepartureclearance.h
        src/Procedure.h
        src/Procedureapproach.h
        src/Procedurearrival.h
        src/Proceduredeparture.h
        src/Procedurename.h
        src/Proceduretransition.h
        src/Proceduretype.h
        src/Publishedidentifier.h
        src/RTArequiredtimearrival.h
        src/RTArequiredtimearrivalsequence.h
        src/RTAtime.h
        src/RTAtolerance.h
        src/Remainingfuel.h
        src/RemainingfuelRemainingsouls.h
        src/Remainingsouls.h
        src/Reportedwaypointaltitude.h
        src/Reportedwaypointposition.h
        src/Reportedwaypointtime.h
        src/Reportingpoints.h
        src/Routeclearance.h
        src/Routeinformation-seqOf.h
        src/Routeinformation.h
        src/Routeinformationadditional.h
        src/Runway.h
        src/Runwayarrival.h
        src/Runwayconfiguration.h
        src/Runwaydeparture.h
        src/Runwaydirection.h
        src/SSRequipmentavailable.h
        src/Speed.h
        src/Speedground.h
        src/Speedgroundmetric.h
        src/Speedindicated.h
        src/Speedindicatedmetric.h
        src/Speedmach.h
        src/Speedmachlarge.h
        src/Speedtrue.h
        src/Speedtruemetric.h
        src/Supplementaryinformation.h
        src/Temperature.h
        src/Temperaturec.h
        src/Temperaturef.h
        src/Time.h
        src/TimeAltitude.h
        src/TimeDistanceTofromPosition.h
        src/TimeDistanceoffsetDirection.h
        src/TimeICAOunitnameFrequency.h
        src/TimePosition.h
        src/TimePositionAltitude.h
        src/TimePositionAltitudeSpeed.h
        src/TimeSpeed.h
        src/TimeSpeedSpeed.h
        src/Timeatpositioncurrent.h
        src/Timedepartureedct.h
        src/Timeetaatfixnext.h
        src/Timeetadestination.h
        src/Timehours.h
        src/Timeminutes.h
        src/Timeseconds.h
        src/Timestamp.h
        src/Timetolerance.h
        src/Tofrom.h
        src/TofromPosition.h
        src/Tp4table.h
        src/Trackangle.h
        src/Trackdetail.h
        src/Trackname.h
        src/Trueheading.h
        src/Turbulence.h
        src/UM0NULL.h
        src/UM100TimeSpeed.h
        src/UM101PositionSpeed.h
        src/UM102AltitudeSpeed.h
        src/UM103TimeSpeedSpeed.h
        src/UM104PositionSpeedSpeed.h
        src/UM105AltitudeSpeedSpeed.h
        src/UM106Speed.h
        src/UM107NULL.h
        src/UM108Speed.h
        src/UM109Speed.h
        src/UM10Position.h
        src/UM110SpeedSpeed.h
        src/UM111Speed.h
        src/UM112Speed.h
        src/UM113Speed.h
        src/UM114Speed.h
        src/UM115Speed.h
        src/UM116NULL.h
        src/UM117ICAOunitnameFrequency.h
        src/UM118PositionICAOunitnameFrequency.h
        src/UM119TimeICAOunitnameFrequency.h
        src/UM11Time.h
        src/UM120ICAOunitnameFrequency.h
        src/UM121PositionICAOunitnameFrequency.h
        src/UM122TimeICAOunitnameFrequency.h
        src/UM123Beaconcode.h
        src/UM124NULL.h
        src/UM125NULL.h
        src/UM126NULL.h
        src/UM127NULL.h
        src/UM128Altitude.h
        src/UM129Altitude.h
        src/UM12Position.h
        src/UM130Position.h
        src/UM131NULL.h
        src/UM132NULL.h
        src/UM133NULL.h
        src/UM134NULL.h
        src/UM135NULL.h
        src/UM136NULL.h
        src/UM137NULL.h
        src/UM138NULL.h
        src/UM139NULL.h
        src/UM13TimeAltitude.h
        src/UM140NULL.h
        src/UM141NULL.h
        src/UM142NULL.h
        src/UM143NULL.h
        src/UM144NULL.h
        src/UM145NULL.h
        src/UM146NULL.h
        src/UM147NULL.h
        src/UM148Altitude.h
        src/UM149AltitudePosition.h
        src/UM14PositionAltitude.h
        src/UM150AltitudeTime.h
        src/UM151Speed.h
        src/UM152DistanceoffsetDirection.h
        src/UM153Altimeter.h
        src/UM154NULL.h
        src/UM155Position.h
        src/UM156NULL.h
        src/UM157Frequency.h
        src/UM158Atiscode.h
        src/UM159Errorinformation.h
        src/UM15TimeAltitude.h
        src/UM160ICAOfacilitydesignation.h
        src/UM161NULL.h
        src/UM162NULL.h
        src/UM163ICAOfacilitydesignationTp4table.h
        src/UM164NULL.h
        src/UM165NULL.h
        src/UM166NULL.h
        src/UM167NULL.h
        src/UM168NULL.h
        src/UM169Freetext.h
        src/UM16PositionAltitude.h
        src/UM170Freetext.h
        src/UM171Verticalrate.h
        src/UM172Verticalrate.h
        src/UM173Verticalrate.h
        src/UM174Verticalrate.h
        src/UM175Altitude.h
        src/UM176NULL.h
        src/UM177NULL.h
        src/UM178NULL.h
        src/UM179NULL.h
        src/UM17TimeAltitude.h
        src/UM180AltitudeAltitude.h
        src/UM181TofromPosition.h
        src/UM182NULL.h
        src/UM18PositionAltitude.h
        src/UM19Altitude.h
        src/UM1NULL.h
        src/UM20Altitude.h
        src/UM21TimeAltitude.h
        src/UM22PositionAltitude.h
        src/UM23Altitude.h
        src/UM24TimeAltitude.h
        src/UM25PositionAltitude.h
        src/UM26AltitudeTime.h
        src/UM27AltitudePosition.h
        src/UM28AltitudeTime.h
        src/UM29AltitudePosition.h
        src/UM2NULL.h
        src/UM30AltitudeAltitude.h
        src/UM31AltitudeAltitude.h
        src/UM32AltitudeAltitude.h
        src/UM33Altitude.h
        src/UM34Altitude.h
        src/UM35Altitude.h
        src/UM36Altitude.h
        src/UM37Altitude.h
        src/UM38Altitude.h
        src/UM39Altitude.h
        src/UM3NULL.h
        src/UM40Altitude.h
        src/UM41Altitude.h
        src/UM42PositionAltitude.h
        src/UM43PositionAltitude.h
        src/UM44PositionAltitude.h
        src/UM45PositionAltitude.h
        src/UM46PositionAltitude.h
        src/UM47PositionAltitude.h
        src/UM48PositionAltitude.h
        src/UM49PositionAltitude.h
        src/UM4NULL.h
        src/UM50PositionAltitudeAltitude.h
        src/UM51PositionTime.h
        src/UM52PositionTime.h
        src/UM53PositionTime.h
        src/UM54PositionTimeTime.h
        src/UM55PositionSpeed.h
        src/UM56PositionSpeed.h
        src/UM57PositionSpeed.h
        src/UM58PositionTimeAltitude.h
        src/UM59PositionTimeAltitude.h
        src/UM5NULL.h
        src/UM60PositionTimeAltitude.h
        src/UM61PositionAltitudeSpeed.h
        src/UM62TimePositionAltitude.h
        src/UM63TimePositionAltitudeSpeed.h
        src/UM64DistanceoffsetDirection.h
        src/UM65PositionDistanceoffsetDirection.h
        src/UM66TimeDistanceoffsetDirection.h
        src/UM67NULL.h
        src/UM68Position.h
        src/UM69Time.h
        src/UM6Altitude.h
        src/UM70Position.h
        src/UM71Time.h
        src/UM72NULL.h
        src/UM73Predepartureclearance.h
        src/UM74Position.h
        src/UM75Position.h
        src/UM76TimePosition.h
        src/UM77PositionPosition.h
        src/UM78AltitudePosition.h
        src/UM79PositionRouteclearance.h
        src/UM7Time.h
        src/UM80Routeclearance.h
        src/UM81Procedurename.h
        src/UM82DistanceoffsetDirection.h
        src/UM83PositionRouteclearance.h
        src/UM84PositionProcedurename.h
        src/UM85Routeclearance.h
        src/UM86PositionRouteclearance.h
        src/UM87Position.h
        src/UM88PositionPosition.h
        src/UM89TimePosition.h
        src/UM8Position.h
        src/UM90AltitudePosition.h
        src/UM91Holdclearance.h
        src/UM92PositionAltitude.h
        src/UM93Time.h
        src/UM94DirectionDegrees.h
        src/UM95DirectionDegrees.h
        src/UM96NULL.h
        src/UM97PositionDegrees.h
        src/UM98DirectionDegrees.h
        src/UM99Procedurename.h
        src/UM9Time.h
        src/Versionnumber.h
        src/Verticalchange.h
        src/Verticaldirection.h
        src/Verticalrate.h
        src/Verticalrateenglish.h
        src/Verticalratemetric.h
        src/Waypointspeedaltitude.h
        src/Waypointspeedaltitudesequence.h
        src/Winddirection.h
        src/Winds.h
        src/Windspeed.h
        src/Windspeedenglish.h
        src/Windspeedmetric.h
        src/asn_SEQUENCE_OF.h
        src/asn_SET_OF.h
        src/asn_application.h
        src/asn_codecs.h
        src/asn_codecs_prim.h
        src/asn_internal.h
        src/asn_system.h
        src/ber_decoder.h
        src/ber_tlv_length.h
        src/ber_tlv_tag.h
        src/constr_CHOICE.h
        src/constr_SEQUENCE.h
        src/constr_SEQUENCE_OF.h
        src/constr_SET_OF.h
        src/constr_TYPE.h
        src/constraints.h
        src/der_encoder.h
        src/per_decoder.h
        src/per_encoder.h
        src/per_opentype.h
        src/per_support.h
        src/xer_decoder.h
        src/xer_encoder.h
        src/xer_support.h
        src/ATCdownlinkmessage.c
        src/ATCdownlinkmsgelementid.c
        src/ATCmessageheader.c
        src/ATCuplinkmessage.c
        src/ATCuplinkmsgelementid-seqOf.c
        src/ATCuplinkmsgelementid.c
        src/ATWDistancetolerance.c
        src/ATWalongtrackwaypoint.c
        src/ATWalongtrackwaypointsequence.c
        src/ATWaltitude.c
        src/ATWaltitudesequence.c
        src/ATWaltitudetolerance.c
        src/ATWdistance.c
        src/Aircraftequipmentcode.c
        src/Aircraftflightidentification.c
        src/Aircrafttype.c
        src/Airport.c
        src/Airportdeparture.c
        src/Airportdestination.c
        src/Airwayidentifier.c
        src/Airwayintercept.c
        src/Altimeter.c
        src/Altimeterenglish.c
        src/Altimetermetric.c
        src/Altitude.c
        src/AltitudePosition.c
        src/AltitudeSpeed.c
        src/AltitudeSpeedSpeed.c
        src/AltitudeTime.c
        src/Altitudeflightlevel.c
        src/Altitudeflightlevelmetric.c
        src/Altitudegnssfeet.c
        src/Altitudegnssmeters.c
        src/Altitudeqfe.c
        src/Altitudeqfemeters.c
        src/Altitudeqnh.c
        src/Altitudeqnhmeters.c
        src/Altituderestriction.c
        src/Atiscode.c
        src/BIT_STRING.c
        src/BOOLEAN.c
        src/Beaconcode.c
        src/Beaconcodeoctaldigit.c
        src/COMNAVapproachequipmentavailable.c
        src/COMNAVequipmentstatus.c
        src/DM0NULL.c
        src/DM100NULL.c
        src/DM101NULL.c
        src/DM102NULL.c
        src/DM103NULL.c
        src/DM104NULL.c
        src/DM105NULL.c
        src/DM106NULL.c
        src/DM107NULL.c
        src/DM108NULL.c
        src/DM109NULL.c
        src/DM10Altitude.c
        src/DM110NULL.c
        src/DM111NULL.c
        src/DM112NULL.c
        src/DM113NULL.c
        src/DM114NULL.c
        src/DM115NULL.c
        src/DM116NULL.c
        src/DM117NULL.c
        src/DM118NULL.c
        src/DM119NULL.c
        src/DM11PositionAltitude.c
        src/DM120NULL.c
        src/DM121NULL.c
        src/DM122NULL.c
        src/DM123NULL.c
        src/DM124NULL.c
        src/DM125NULL.c
        src/DM126NULL.c
        src/DM127NULL.c
        src/DM128NULL.c
        src/DM12PositionAltitude.c
        src/DM13TimeAltitude.c
        src/DM14TimeAltitude.c
        src/DM15DistanceoffsetDirection.c
        src/DM16PositionDistanceoffsetDirection.c
        src/DM17TimeDistanceoffsetDirection.c
        src/DM18Speed.c
        src/DM19SpeedSpeed.c
        src/DM1NULL.c
        src/DM20NULL.c
        src/DM21Frequency.c
        src/DM22Position.c
        src/DM23Procedurename.c
        src/DM24Routeclearance.c
        src/DM25NULL.c
        src/DM26PositionRouteclearance.c
        src/DM27DistanceoffsetDirection.c
        src/DM28Altitude.c
        src/DM29Altitude.c
        src/DM2NULL.c
        src/DM30Altitude.c
        src/DM31Position.c
        src/DM32Altitude.c
        src/DM33Position.c
        src/DM34Speed.c
        src/DM35Degrees.c
        src/DM36Degrees.c
        src/DM37Altitude.c
        src/DM38Altitude.c
        src/DM39Speed.c
        src/DM3NULL.c
        src/DM40Routeclearance.c
        src/DM41NULL.c
        src/DM42Position.c
        src/DM43Time.c
        src/DM44Position.c
        src/DM45Position.c
        src/DM46Time.c
        src/DM47Beaconcode.c
        src/DM48Positionreport.c
        src/DM49Speed.c
        src/DM4NULL.c
        src/DM50SpeedSpeed.c
        src/DM51NULL.c
        src/DM52NULL.c
        src/DM53NULL.c
        src/DM54Altitude.c
        src/DM55NULL.c
        src/DM56NULL.c
        src/DM57RemainingfuelRemainingsouls.c
        src/DM58NULL.c
        src/DM59PositionRouteclearance.c
        src/DM5NULL.c
        src/DM60DistanceoffsetDirection.c
        src/DM61Altitude.c
        src/DM62Errorinformation.c
        src/DM63NULL.c
        src/DM64ICAOfacilitydesignation.c
        src/DM65NULL.c
        src/DM66NULL.c
        src/DM67Freetext.c
        src/DM68Freetext.c
        src/DM69NULL.c
        src/DM6Altitude.c
        src/DM70Degrees.c
        src/DM71Degrees.c
        src/DM72Altitude.c
        src/DM73Versionnumber.c
        src/DM74NULL.c
        src/DM75NULL.c
        src/DM76AltitudeAltitude.c
        src/DM77AltitudeAltitude.c
        src/DM78TimeDistanceTofromPosition.c
        src/DM79Atiscode.c
        src/DM7AltitudeAltitude.c
        src/DM80DistanceoffsetDirection.c
        src/DM81NULL.c
        src/DM82NULL.c
        src/DM83NULL.c
        src/DM84NULL.c
        src/DM85NULL.c
        src/DM86NULL.c
        src/DM87NULL.c
        src/DM88NULL.c
        src/DM89NULL.c
        src/DM8Altitude.c
        src/DM90NULL.c
        src/DM91NULL.c
        src/DM92NULL.c
        src/DM93NULL.c
        src/DM94NULL.c
        src/DM95NULL.c
        src/DM96NULL.c
        src/DM97NULL.c
        src/DM98NULL.c
        src/DM99NULL.c
        src/DM9Altitude.c
        src/Degreeincrement.c
        src/Degrees.c
        src/Degreesmagnetic.c
        src/Degreestrue.c
        src/Direction.c
        src/DirectionDegrees.c
        src/Distance.c
        src/Distancekm.c
        src/Distancenm.c
        src/Distanceoffset.c
        src/DistanceoffsetDirection.c
        src/Distanceoffsetkm.c
        src/Distanceoffsetnm.c
        src/EFCtime.c
        src/Errorinformation.c
        src/Fixname.c
        src/Fixnext.c
        src/Fixnextplusone.c
        src/Freetext.c
        src/Frequency.c
        src/Frequencydeparture.c
        src/Frequencyhf.c
        src/Frequencysatchannel.c
        src/Frequencyuhf.c
        src/Frequencyvhf.c
        src/Holdatwaypoint.c
        src/Holdatwaypointsequence.c
        src/Holdatwaypointspeedhigh.c
        src/Holdatwaypointspeedlow.c
        src/Holdclearance.c
        src/IA5String.c
        src/ICAOfacilitydesignation.c
        src/ICAOfacilitydesignationTp4table.c
        src/ICAOfacilityfunction.c
        src/ICAOfacilityidentification.c
        src/ICAOfacilityname.c
        src/ICAOunitname.c
        src/ICAOunitnameFrequency.c
        src/INTEGER.c
        src/Icing.c
        src/Interceptcoursefrom.c
        src/Interceptcoursefromselection.c
        src/Interceptcoursefromsequence.c
        src/Latitude.c
        src/LatitudeLongitude.c
        src/Latitudedegrees.c
        src/Latitudedirection.c
        src/Latitudereportingpoints.c
        src/Latlonreportingpoints.c
        src/Legdistance.c
        src/Legdistanceenglish.c
        src/Legdistancemetric.c
        src/Legtime.c
        src/Legtype.c
        src/Longitude.c
        src/Longitudedegrees.c
        src/Longitudedirection.c
        src/Longitudereportingpoints.c
        src/Minuteslatlon.c
        src/Msgidentificationnumber.c
        src/Msgreferencenumber.c
        src/NULL.c
        src/NativeEnumerated.c
        src/NativeInteger.c
        src/Navaid.c
        src/NumericString.c
        src/OCTET_STRING.c
        src/PDCrevision.c
        src/Placebearing.c
        src/Placebearingdistance.c
        src/Placebearingplacebearing.c
        src/Position.c
        src/PositionAltitude.c
        src/PositionAltitudeAltitude.c
        src/PositionAltitudeSpeed.c
        src/PositionDegrees.c
        src/PositionDistanceoffsetDirection.c
        src/PositionICAOunitnameFrequency.c
        src/PositionProcedurename.c
        src/PositionRouteclearance.c
        src/PositionSpeed.c
        src/PositionSpeedSpeed.c
        src/PositionTime.c
        src/PositionTimeAltitude.c
        src/PositionTimeTime.c
        src/Positioncurrent.c
        src/Positionreport.c
        src/Predepartureclearance.c
        src/Procedure.c
        src/Procedureapproach.c
        src/Procedurearrival.c
        src/Proceduredeparture.c
        src/Procedurename.c
        src/Proceduretransition.c
        src/Proceduretype.c
        src/Publishedidentifier.c
        src/RTArequiredtimearrival.c
        src/RTArequiredtimearrivalsequence.c
        src/RTAtime.c
        src/RTAtolerance.c
        src/Remainingfuel.c
        src/RemainingfuelRemainingsouls.c
        src/Remainingsouls.c
        src/Reportedwaypointaltitude.c
        src/Reportedwaypointposition.c
        src/Reportedwaypointtime.c
        src/Reportingpoints.c
        src/Routeclearance.c
        src/Routeinformation-seqOf.c
        src/Routeinformation.c
        src/Routeinformationadditional.c
        src/Runway.c
        src/Runwayarrival.c
        src/Runwayconfiguration.c
        src/Runwaydeparture.c
        src/Runwaydirection.c
        src/SSRequipmentavailable.c
        src/Speed.c
        src/Speedground.c
        src/Speedgroundmetric.c
        src/Speedindicated.c
        src/Speedindicatedmetric.c
        src/Speedmach.c
        src/Speedmachlarge.c
        src/Speedtrue.c
        src/Speedtruemetric.c
        src/Supplementaryinformation.c
        src/Temperature.c
        src/Temperaturec.c
        src/Temperaturef.c
        src/Time.c
        src/TimeAltitude.c
        src/TimeDistanceTofromPosition.c
        src/TimeDistanceoffsetDirection.c
        src/TimeICAOunitnameFrequency.c
        src/TimePosition.c
        src/TimePositionAltitude.c
        src/TimePositionAltitudeSpeed.c
        src/TimeSpeed.c
        src/TimeSpeedSpeed.c
        src/Timeatpositioncurrent.c
        src/Timedepartureedct.c
        src/Timeetaatfixnext.c
        src/Timeetadestination.c
        src/Timehours.c
        src/Timeminutes.c
        src/Timeseconds.c
        src/Timestamp.c
        src/Timetolerance.c
        src/Tofrom.c
        src/TofromPosition.c
        src/Tp4table.c
        src/Trackangle.c
        src/Trackdetail.c
        src/Trackname.c
        src/Trueheading.c
        src/Turbulence.c
        src/UM0NULL.c
        src/UM100TimeSpeed.c
        src/UM101PositionSpeed.c
        src/UM102AltitudeSpeed.c
        src/UM103TimeSpeedSpeed.c
        src/UM104PositionSpeedSpeed.c
        src/UM105AltitudeSpeedSpeed.c
        src/UM106Speed.c
        src/UM107NULL.c
        src/UM108Speed.c
        src/UM109Speed.c
        src/UM10Position.c
        src/UM110SpeedSpeed.c
        src/UM111Speed.c
        src/UM112Speed.c
        src/UM113Speed.c
        src/UM114Speed.c
        src/UM115Speed.c
        src/UM116NULL.c
        src/UM117ICAOunitnameFrequency.c
        src/UM118PositionICAOunitnameFrequency.c
        src/UM119TimeICAOunitnameFrequency.c
        src/UM11Time.c
        src/UM120ICAOunitnameFrequency.c
        src/UM121PositionICAOunitnameFrequency.c
        src/UM122TimeICAOunitnameFrequency.c
        src/UM123Beaconcode.c
        src/UM124NULL.c
        src/UM125NULL.c
        src/UM126NULL.c
        src/UM127NULL.c
        src/UM128Altitude.c
        src/UM129Altitude.c
        src/UM12Position.c
        src/UM130Position.c
        src/UM131NULL.c
        src/UM132NULL.c
        src/UM133NULL.c
        src/UM134NULL.c
        src/UM135NULL.c
        src/UM136NULL.c
        src/UM137NULL.c
        src/UM138NULL.c
        src/UM139NULL.c
        src/UM13TimeAltitude.c
        src/UM140NULL.c
        src/UM141NULL.c
        src/UM142NULL.c
        src/UM143NULL.c
        src/UM144NULL.c
        src/UM145NULL.c
        src/UM146NULL.c
        src/UM147NULL.c
        src/UM148Altitude.c
        src/UM149AltitudePosition.c
        src/UM14PositionAltitude.c
        src/UM150AltitudeTime.c
        src/UM151Speed.c
        src/UM152DistanceoffsetDirection.c
        src/UM153Altimeter.c
        src/UM154NULL.c
        src/UM155Position.c
        src/UM156NULL.c
        src/UM157Frequency.c
        src/UM158Atiscode.c
        src/UM159Errorinformation.c
        src/UM15TimeAltitude.c
        src/UM160ICAOfacilitydesignation.c
        src/UM161NULL.c
        src/UM162NULL.c
        src/UM163ICAOfacilitydesignationTp4table.c
        src/UM164NULL.c
        src/UM165NULL.c
        src/UM166NULL.c
        src/UM167NULL.c
        src/UM168NULL.c
        src/UM169Freetext.c
        src/UM16PositionAltitude.c
        src/UM170Freetext.c
        src/UM171Verticalrate.c
        src/UM172Verticalrate.c
        src/UM173Verticalrate.c
        src/UM174Verticalrate.c
        src/UM175Altitude.c
        src/UM176NULL.c
        src/UM177NULL.c
        src/UM178NULL.c
        src/UM179NULL.c
        src/UM17TimeAltitude.c
        src/UM180AltitudeAltitude.c
        src/UM181TofromPosition.c
        src/UM182NULL.c
        src/UM18PositionAltitude.c
        src/UM19Altitude.c
        src/UM1NULL.c
        src/UM20Altitude.c
        src/UM21TimeAltitude.c
        src/UM22PositionAltitude.c
        src/UM23Altitude.c
        src/UM24TimeAltitude.c
        src/UM25PositionAltitude.c
        src/UM26AltitudeTime.c
        src/UM27AltitudePosition.c
        src/UM28AltitudeTime.c
        src/UM29AltitudePosition.c
        src/UM2NULL.c
        src/UM30AltitudeAltitude.c
        src/UM31AltitudeAltitude.c
        src/UM32AltitudeAltitude.c
        src/UM33Altitude.c
        src/UM34Altitude.c
        src/UM35Altitude.c
        src/UM36Altitude.c
        src/UM37Altitude.c
        src/UM38Altitude.c
        src/UM39Altitude.c
        src/UM3NULL.c
        src/UM40Altitude.c
        src/UM41Altitude.c
        src/UM42PositionAltitude.c
        src/UM43PositionAltitude.c
        src/UM44PositionAltitude.c
        src/UM45PositionAltitude.c
        src/UM46PositionAltitude.c
        src/UM47PositionAltitude.c
        src/UM48PositionAltitude.c
        src/UM49PositionAltitude.c
        src/UM4NULL.c
        src/UM50PositionAltitudeAltitude.c
        src/UM51PositionTime.c
        src/UM52PositionTime.c
        src/UM53PositionTime.c
        src/UM54PositionTimeTime.c
        src/UM55PositionSpeed.c
        src/UM56PositionSpeed.c
        src/UM57PositionSpeed.c
        src/UM58PositionTimeAltitude.c
        src/UM59PositionTimeAltitude.c
        src/UM5NULL.c
        src/UM60PositionTimeAltitude.c
        src/UM61PositionAltitudeSpeed.c
        src/UM62TimePositionAltitude.c
        src/UM63TimePositionAltitudeSpeed.c
        src/UM64DistanceoffsetDirection.c
        src/UM65PositionDistanceoffsetDirection.c
        src/UM66TimeDistanceoffsetDirection.c
        src/UM67NULL.c
        src/UM68Position.c
        src/UM69Time.c
        src/UM6Altitude.c
        src/UM70Position.c
        src/UM71Time.c
        src/UM72NULL.c
        src/UM73Predepartureclearance.c
        src/UM74Position.c
        src/UM75Position.c
        src/UM76TimePosition.c
        src/UM77PositionPosition.c
        src/UM78AltitudePosition.c
        src/UM79PositionRouteclearance.c
        src/UM7Time.c
        src/UM80Routeclearance.c
        src/UM81Procedurename.c
        src/UM82DistanceoffsetDirection.c
        src/UM83PositionRouteclearance.c
        src/UM84PositionProcedurename.c
        src/UM85Routeclearance.c
        src/UM86PositionRouteclearance.c
        src/UM87Position.c
        src/UM88PositionPosition.c
        src/UM89TimePosition.c
        src/UM8Position.c
        src/UM90AltitudePosition.c
        src/UM91Holdclearance.c
        src/UM92PositionAltitude.c
        src/UM93Time.c
        src/UM94DirectionDegrees.c
        src/UM95DirectionDegrees.c
        src/UM96NULL.c
        src/UM97PositionDegrees.c
        src/UM98DirectionDegrees.c
        src/UM99Procedurename.c
        src/UM9Time.c
        src/Versionnumber.c
        src/Verticalchange.c
        src/Verticaldirection.c
        src/Verticalrate.c
        src/Verticalrateenglish.c
        src/Verticalratemetric.c
        src/Waypointspeedaltitude.c
        src/Waypointspeedaltitudesequence.c
        src/Winddirection.c
        src/Winds.c
        src/Windspeed.c
        src/Windspeedenglish.c
        src/Windspeedmetric.c
        src/asn_SEQUENCE_OF.c
        src/asn_SET_OF.c
        src/asn_codecs_prim.c
        src/ber_decoder.c
        src/ber_tlv_length.c
        src/ber_tlv_tag.c
        src/constr_CHOICE.c
        src/constr_SEQUENCE.c
        src/constr_SEQUENCE_OF.c
        src/constr_SET_OF.c
        src/constr_TYPE.c
        src/constraints.c
        src/der_encoder.c
        src/per_decoder.c
        src/per_encoder.c
        src/per_opentype.c
        src/per_support.c
        src/xer_decoder.c
        src/xer_encoder.c
        src/xer_support.c
    )
endif()
