/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "../cpdlc.asn"
 * 	`asn1c -S /home/alex/src/asn1c/skeletons/ -fcompound-names`
 */

#ifndef	_Routeinformation_seqOf_H_
#define	_Routeinformation_seqOf_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Routeinformation;

/* Routeinformation-seqOf */
typedef struct Routeinformation_seqOf {
	A_SEQUENCE_OF(struct Routeinformation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Routeinformation_seqOf_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Routeinformation_seqOf;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Routeinformation.h"

#endif	/* _Routeinformation_seqOf_H_ */
#include <asn_internal.h>
