/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "../cpdlc.asn"
 * 	`asn1c -S /home/alex/src/asn1c/skeletons/ -fcompound-names`
 */

#include "Routeclearance.h"

static asn_TYPE_member_t asn_MBR_Routeclearance_1[] = {
	{ ATF_POINTER, 10, offsetof(struct Routeclearance, airportdeparture),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Airportdeparture,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"airportdeparture"
		},
	{ ATF_POINTER, 9, offsetof(struct Routeclearance, airportdestination),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Airportdestination,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"airportdestination"
		},
	{ ATF_POINTER, 8, offsetof(struct Routeclearance, runwaydeparture),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Runwaydeparture,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"runwaydeparture"
		},
	{ ATF_POINTER, 7, offsetof(struct Routeclearance, proceduredeparture),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Proceduredeparture,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proceduredeparture"
		},
	{ ATF_POINTER, 6, offsetof(struct Routeclearance, runwayarrival),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Runwayarrival,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"runwayarrival"
		},
	{ ATF_POINTER, 5, offsetof(struct Routeclearance, procedureapproach),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Procedureapproach,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"procedureapproach"
		},
	{ ATF_POINTER, 4, offsetof(struct Routeclearance, procedurearrival),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Procedurearrival,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"procedurearrival"
		},
	{ ATF_POINTER, 3, offsetof(struct Routeclearance, airwayintercept),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Airwayintercept,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"airwayintercept"
		},
	{ ATF_POINTER, 2, offsetof(struct Routeclearance, routeinformation_seqOf),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Routeinformation_seqOf,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"routeinformation-seqOf"
		},
	{ ATF_POINTER, 1, offsetof(struct Routeclearance, routeinformationadditional),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Routeinformationadditional,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"routeinformationadditional"
		},
};
static const int asn_MAP_Routeclearance_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_Routeclearance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Routeclearance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* airportdeparture */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* airportdestination */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* runwaydeparture */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* proceduredeparture */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* runwayarrival */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* procedureapproach */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* procedurearrival */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* airwayintercept */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* routeinformation-seqOf */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* routeinformationadditional */
};
static asn_SEQUENCE_specifics_t asn_SPC_Routeclearance_specs_1 = {
	sizeof(struct Routeclearance),
	offsetof(struct Routeclearance, _asn_ctx),
	asn_MAP_Routeclearance_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_Routeclearance_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Routeclearance = {
	"Routeclearance",
	"Routeclearance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Routeclearance_tags_1,
	sizeof(asn_DEF_Routeclearance_tags_1)
		/sizeof(asn_DEF_Routeclearance_tags_1[0]), /* 1 */
	asn_DEF_Routeclearance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Routeclearance_tags_1)
		/sizeof(asn_DEF_Routeclearance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Routeclearance_1,
	10,	/* Elements count */
	&asn_SPC_Routeclearance_specs_1	/* Additional specs */
};

