get_filename_component(AFTNCATALOGORGANIZER_CURRENTDIR ${CMAKE_CURRENT_LIST_FILE} PATH)

include_directories("${AFTNCATALOGORGANIZER_CURRENTDIR}/src")
    
list(APPEND HEADERS "${AFTNCATALOGORGANIZER_CURRENTDIR}/src/catalogorganizer.h")

list(APPEND SOURCES "${AFTNCATALOGORGANIZER_CURRENTDIR}/src/catalogorganizer.cpp")
